# Extra autostart processe


# exec-once = uwsm app -- my-servic### Workspace 5 uses Master layout (master is left by default)
workspace = 4, layout master

### Send Slack & Teams to workspace 5 and keep them tiled
windowrulev2 = workspace 4, class:^(Slack)$
windowrulev2 = workspace 4, class:^(Microsoft Teams.*|Teams)$
windowrulev2 = tile,      class:^(Slack)$
windowrulev2 = tile,      class:^(Microsoft Teams.*|Teams)$


exec-once = bash -lc '~/.config/hypr/watch-slack-teams.sh'

