# Extra autostart processe


# exec-once = uwsm app -- my-servic### Workspace 5 uses Master layout (master is left by default)
# workspace = 4, layout master
# Workspace 1 & 4 -> Center Monitor
workspace = 2, monitor:DP-2, default:true
workspace = 5, monitor:DP-2, layout:master

# Workspace 2 & 5 -> Right Monitor
workspace = 3, monitor:HDMI-A-1, default:true
workspace = 6, monitor:HDMI-A-1

# Workspace 3 & 6 -> Left Monitor
workspace = 1, monitor:DP-1, default:true
workspace = 4, monitor:DP-1

exec-once = hyprctl dispatch focusmonitor DP-3


exec-once = bash -lc '~/.config/hypr/watch-slack-teams.sh'

